MODEL:
  CONTRASTIVE: "moco"
  MOCO_K: 4096
OUTPUT_DIR: "../models/moco_resnet18_cifar10_64_4096/"
SOLVER:
  BATCH_SIZE: 64

GPU: 0                      # Only gpu mode is supported now
DISTRIBUTED: True
MULTIPROC_DIST: True
DIST_URL: 'tcp://10.198.87.144:8008'
# _C.DIST_URL = 'tcp://224.66.41.62:23456'
DIST_BACKEND: 'nccl'
WORLD_SIZE: 2
RANK: 0